mindvalley/wukong-cli

- .github/PULL_REQUEST_TEMPLATE.md
- src/error.rs
- src/graphql/pipeline.rs
The error message for `wukong pipeline ci-status` command is very confusing. This PR will display a more meaningful error message and suggestion.
Ticket: [PXP-389](https://mindvalley.atlassian.net/browse/PXP-389)
> PXP-389: Display better error message when cannot detect working folder

- src/commands/deployment/execute.rs
- src/graphql/changelog.rs
- src/graphql/query/cd_pipeline.graphql
- src/graphql/schema.json
Ticket: [PXP-411](https://mindvalley.atlassian.net/browse/PXP-411)
(Not critical) The layout will be a bit off in narrow window or when the commit headline is too long
> PXP-411: [CLI] Support render more than 1 commit in the build artifacts listing step

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- Cross.toml
- src/app.rs
- src/auth/mod.rs
- src/commands/config.rs
- src/commands/init.rs
- src/config.rs
- src/error.rs
- src/graphql/mod.rs
- src/main.rs
- src/output/error.rs
Ticket: [PXP-416](https://mindvalley.atlassian.net/browse/PXP-416)
User will get the message if they updated to this version but using the old `config.toml` values:
They have to remove the existing `config.toml` file and run `wukong init` to re-initialise the config then it should be all good.
- `cargo run --features prod -- command` will use the prod values
> PXP-416: [Wukong CLI] Allowing to override the api_url and okta_client_id in the config

- src/commands/deployment/list.rs
Ticket: [PXP-424](https://mindvalley.atlassian.net/browse/PXP-424)
> PXP-424: [CLI] Use Short Commit Hash rather than full commit hash

- src/commands/deployment/execute.rs
- src/error.rs
The namespace selections always show `Prod` and `Staging`, and the version selections always show `Blue` and `Green` even if the current application doesn't have that namespace/version. Now the selections will be based on the API result.
If the user is using `--namespace` or `--version` flag but the value provided is not available for the current application, the cli will return `DeploymentError`.
Ticket: [PXP-417](https://mindvalley.atlassian.net/browse/PXP-417)
> PXP-417: [Wukong CLI] Don't display selection if it's not available for an application

- src/commands/deployment/list.rs
- src/graphql/query/cd_pipelines.graphql
- src/graphql/schema.json
Ticket: [PXP-428](https://mindvalley.atlassian.net/browse/PXP-428)
> PXP-428: [CLI] Display the Trigger User when listing deployments

- src/graphql/deployment.rs
Ticket: [PXP-436](https://mindvalley.atlassian.net/browse/PXP-436)
> PXP-436: [Wukong CLI] Display message to tell user that there are a deployment with same arguments is running

- src/commands/deployment/execute.rs
- src/graphql/query/cd_pipeline.graphql
- src/graphql/schema.json
Ticket: [PXP-426](https://mindvalley.atlassian.net/browse/PXP-426)
* This is using this [PR](https://github.com/mindvalley/wukong-api-proxy/pull/47) as backend to get the `buildBranch` value
- if the build selection list contains the current build, it will display in 3 columns layout
- if the current `build_artifact` is not in `{branch}-build-{build_number}` pattern, or the build selection list doesn't contain the current build, it will display in 2 columns layout
> PXP-426: [CLI] Show which build artifact is the current deployed one when selecting artifact

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/telemetry.rs
Previously the development environment and production environment share the same config file path, this cause a lot of confusion even for me. This PR adds a config file path for the development environment (`~/.config/wukong/dev/config.toml`). Running wukong without `prod` features, which only happens during development, will use the development environment config file.
Ticket:
> Add config file for development environment

- Cargo.toml
- src/graphql/application.rs
- src/graphql/changelog.rs
- src/graphql/deployment.rs
- src/graphql/mod.rs
- src/graphql/pipeline.rs
- src/main.rs
Ticket: [PXP-445](https://mindvalley.atlassian.net/browse/PXP-445)
[PXP-445]: https://mindvalley.atlassian.net/browse/PXP-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-445: [CLI] Printing DEBUG log from the CLI

- src/auth/mod.rs
Add a debug log when refreshing token failed. This should allow us to know the exact error when the error happen again.
Ticket: [PXP-494](https://mindvalley.atlassian.net/browse/PXP-494)
[PXP-494]: https://mindvalley.atlassian.net/browse/PXP-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-494: [Wukong CLI] Improving the debug log for Okta refresh token flow

- .github/workflows/release.yml
> fix: remove unused step for macos

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/error.rs
- src/services/vault/mod.rs
Previously, when the module is initialised, module take care of whole login flow. However that might create side effects so we have detach the login flow with main functions and exposed the `get_token_or_login` to use before calling the api
Ticket: [PXP-466](https://mindvalley.atlassian.net/browse/PXP-466)
[PXP-466]: https://mindvalley.atlassian.net/browse/PXP-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-475: [Wukong CLI] Refactor auth logic

- src/error.rs
- src/graphql/mod.rs
In this PR, we introduce a `retry` mechanism for requests that `timeout`.  If a request to our third-party APIs timeout, the request is retried up to 3 times (waiting 5 seconds after each attempt).
xtTicket: https://mindvalley.atlassian.net/browse/PXP-489
> PXP-489 retry request on query timeout

- src/commands/dev/config/push.rs
- src/services/vault/client.rs
This merge request introduces the implementation of the PATCH API method for updating secrets in Bunker through the Wukong CLI. The motivation behind this enhancement is to leverage the latest version of Vault (>1.9.0) and its new endpoint, which allows updating secrets without sending the full payload.
Patch Endpoint Documentation: [Patch Secret Endpoint](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#patch-secret)
Ticket: [PXP-530](https://mindvalley.atlassian.net/browse/PXP-530)
[PXP-530]: https://mindvalley.atlassian.net/browse/PXP-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-530: [CLI] Support PATCH API for updating secrets in Bunker

- src/commands/application/instances/connect.rs
This PR addresses an issue encountered during the livebook instance connection test, where a Certificate error (from `reqwest`) may occur when the certificate is not yet ready. Currently, this error immediately halts the connection test retry process.
With this PR, we enables retries when encountering a `reqwest` error. In addition, detailed error information will be logged in the debug log.
> Fix the reqwest error to stop the retrying during connection check

- src/config.rs
- src/error.rs
- src/services/vault/client.rs
- src/services/vault/mod.rs
- tests/dev_config.rs
This pull request aims to enhance our Vault integration by implementing auth token renewal using the Vault API's auto-renew endpoint. Currently, wukong cli requires users to manually re-login to Vault after their tokens expire, which can be inconvenient for users making multiple Vault API calls.
Auto-Renew Endpoint Documentation: [Renew a Token (Self)](https://developer.hashicorp.com/vault/api-docs/auth/token#renew-a-token-self)
Ticket: [PXP-538](https://mindvalley.atlassian.net/browse/PXP-538)
[PXP-538]: https://mindvalley.atlassian.net/browse/PXP-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-538: Renew auth token

- src/auth/mod.rs
- src/commands/init.rs
- src/commands/login.rs
- src/commands/mod.rs
- src/error.rs
Ticket: [PXP-547](https://mindvalley.atlassian.net/browse/PXP-547)
[PXP-547]: https://mindvalley.atlassian.net/browse/PXP-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-547: [CLI] The cli is not working when the refresh token is expired.

- src/services/gcloud/mod.rs
Ticket: [PXP-549](https://mindvalley.atlassian.net/browse/PXP-549)
[PXP-549]: https://mindvalley.atlassian.net/browse/PXP-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-549: [API] Google Cloud Oauth2 does not have the resfresh token

- src/commands/application/instances/connect.rs
- src/main.rs
The root cause of this is because we have 2 `ctrl-c` handlers, and they are conflicted with each other. I do a quick fix by removing the first `ctrl-c` handler (the one to show the cursor after `ctrl-c`) because I believe that unable to exit the cli with `ctrl-c` is much more annoying. 
Another solution I can think of is to use other key to close the instance connection, so we won't have the conflict at the first place. 
There are few ways to handle the signal too (https://tokio.rs/tokio/topics/shutdown), but this requires some refactoring. I think we can do this in the v2 implementation.
Ticket: [PXP-548](https://mindvalley.atlassian.net/browse/PXP-548)
[PXP-548]: https://mindvalley.atlassian.net/browse/PXP-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> PXP-548: [CLI] Program does not exit on Ctrl-C key press

- crates/wukong_telemetry_macro/src/lib.rs
- src/commands/application/instances/connect.rs
- src/commands/application/logs.rs
- src/commands/dev/config/diff.rs
- src/commands/dev/config/mod.rs
- src/commands/dev/config/pull.rs
- src/commands/dev/config/push.rs
- src/commands/dev/mod.rs
- src/commands/mod.rs
- tests/dev_config.rs
Ticket: [PXP-571](https://mindvalley.atlassian.net/browse/PXP-571)
[PXP-571]: https://mindvalley.atlassian.net/browse/PXP-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-571: [CLI] Send telemetry data for new command groups

- src/commands/application/instances/connect.rs
- src/commands/deployment/execute.rs
Currently with an application that is having Blue-Green deployment topology, we don’t have an effective method to guarantee that the Blue deployment is running BEFORE sending the Green deployment however Mindvalley does not follow this practice yet so need additional handling to check for the deployment status, and ask for confirmation if there is any failure.
Ticket: [https://mindvalley.atlassian.net/browse/PXP-572](https://mindvalley.atlassian.net/browse/PXP-572)
> PXP-572: Handle blue/green deployment failure on deployment

- cli/src/commands/tui.rs
Spent quite some times to study the docs and other tui product, finally understand how the tui works. This PR is only for the header layout as the shortcut key implementation is on a separated ticket.
Ticket: [PXP-578](https://mindvalley.atlassian.net/browse/PXP-578)
[PXP-578]: https://mindvalley.atlassian.net/browse/PXP-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-578: [CLI] Implement the headers section

- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/ui/logs.rs
- cli/src/commands/tui/ui/namespace_selection.rs
- sdk/src/error.rs
- sdk/src/services/gcloud/mod.rs
Currently TUI breaks if there is an error while fetching the gcloud logs. To avoid that added a handler to handle the logs
Ticket: [https://mindvalley.atlassian.net/browse/PXP-604](https://mindvalley.atlassian.net/browse/PXP-604)
<table role="table">
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
> PXP-604: handle permission error for the TUI

- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/mod.rs
- cli/src/commands/tui/ui/logs.rs
Update the various logics on logs to make sure that wukong TUI to improve the performance on lower end devices
Ticket: https://mindvalley.atlassian.net/browse/PXP-596
> PXP-596: Optimize the logs rendering on tui

- cli/src/commands/application/logs.rs
- cli/src/commands/tui/action.rs
- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/ui/help.rs
- cli/src/commands/tui/ui/logs.rs
Introduce a new hotkey, `Ctrl+e`, to allow showing the errors only. This is equivalent to passing the --errors parameter into the application logs command.
Ticket: https://mindvalley.atlassian.net/browse/PXP-611
> PXP-611: add error logs filter on tui

- cli/src/commands/tui/action.rs
- cli/src/commands/tui/app.rs
- cli/src/commands/tui/ui/help.rs
- cli/src/commands/tui/ui/logs.rs
Introduce a new hot key, Ctrl+t (t stand for tailing), to allow pause / resume the logs tailing. 
When triggered, it will either pause the logs tailing operation, or resuming to tail the logs in the Logs panel.
Ticket: https://mindvalley.atlassian.net/browse/PXP-598
> PXP-598: Add log tailing hotkey

- cli/src/commands/pipeline/ci_status.rs
- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/ui/builds.rs
- cli/src/commands/tui/ui/deployment.rs
- cli/src/commands/tui/ui/logs.rs
- cli/src/commands/tui/ui/namespace_selection.rs
- cli/src/error.rs
- sdk/src/error.rs
- sdk/src/graphql/application.rs
- sdk/src/graphql/changelog.rs
- sdk/src/graphql/deployment.rs
- sdk/src/graphql/deployment_github.rs
- sdk/src/graphql/kubernetes.rs
- sdk/src/graphql/mod.rs
- sdk/src/graphql/pipeline.rs
- sdk/src/services/gcloud/api/google.api.rs
Ticket: [PXP-582](https://mindvalley.atlassian.net/browse/PXP-582) and [PXP-583](https://mindvalley.atlassian.net/browse/PXP-583) 
- The reason why we remove the context in the error value is because we now doing centralized error handling, which we don't know what is the context value in advance (`application`, `name`, `pipeline` and etc.). 
[PXP-583]: https://mindvalley.atlassian.net/browse/PXP-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PXP-582]: https://mindvalley.atlassian.net/browse/PXP-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-583: [CLI] New Error Codes handling

- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/ui/namespace_selection.rs
- cli/src/commands/tui/ui/version_selection.rs
There are few bugs found during my discoveries, so I made a PR to fix them together.
Ticket: [PXP-616](https://mindvalley.atlassian.net/browse/PXP-616)
[PXP-616]: https://mindvalley.atlassian.net/browse/PXP-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-616: [CLI] Log Entries is not reset after a new namespace or a new version is selected

- cli/src/commands/tui/handlers/log_filter_exclude.rs
- cli/src/commands/tui/handlers/log_filter_include.rs
- cli/src/commands/tui/handlers/log_search.rs
- sdk/src/services/gcloud/api/google.api.rs
Previously the user is not able to close filter bar and search bar with `Esc` key. This PR fixes it.
Ticket: [PXP-627](https://mindvalley.atlassian.net/browse/PXP-627)
[PXP-627]: https://mindvalley.atlassian.net/browse/PXP-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-627: [CLI] Key binding is incorrect for the logs panel

- cli/src/commands/tui/ui/help.rs
This PR fix the header layout issue on big screen.
Before:
After: 
Ticket: [PXP-631](https://mindvalley.atlassian.net/browse/PXP-631)
[PXP-631]: https://mindvalley.atlassian.net/browse/PXP-631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-631: [CLI] The header layout is broken on big screen

- cli/src/commands/tui/ui/logs.rs
Sometimes when pressing the Ctrl-e hotkey, the CLI went to panic because the `calculate_start_position` function can result in overflow when `state.logs_table_start_position `exceeds the length of state.log_entries.
Ticket: https://mindvalley.atlassian.net/browse/PXP-630
> PXP-630: [CLI]: fix ctrl+e panic

- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/handlers/empty.rs
- cli/src/commands/tui/handlers/logs.rs
- cli/src/commands/tui/handlers/namespace_selection.rs
- cli/src/commands/tui/handlers/time_filter_selection.rs
- cli/src/commands/tui/handlers/version_selection.rs
- cli/src/commands/tui/ui/logs.rs
- cli/src/output/tokenizer.rs
- sdk/src/services/vault/client.rs
Ticket: [PXP-639](https://mindvalley.atlassian.net/browse/PXP-639)
For example, the `log_entries` type is `(String, Vec<LogEntry>)`, the first value is the ID. Every time the state is changed (Namespace, version, time filter, log severity and etc), a new ID will be generated. And if the API ID is not the same with the latest ID, it won't append to the `Vec`. This prevent the existing outdated API call results pollute the log vector.
[PXP-639]: https://mindvalley.atlassian.net/browse/PXP-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-639: [CLI] Ctrl-e stopped working on the latest codebase

- cli/src/commands/tui/handlers/empty.rs
- cli/src/commands/tui/handlers/logs.rs
- cli/src/commands/tui/handlers/namespace_selection.rs
- cli/src/commands/tui/handlers/time_filter_selection.rs
- cli/src/commands/tui/handlers/version_selection.rs
- cli/src/commands/tui/ui/logs.rs
Ticket: [PXP-640](https://mindvalley.atlassian.net/browse/PXP-640)
[PXP-640]: https://mindvalley.atlassian.net/browse/PXP-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-640: [CLI] Log panel panic when the start index out of bound

- sdk/src/graphql/mod.rs
Currently the Wukong CLI is expecting a proper response which are defined on the grapql schema. If the response is diff it throws an error with this error
`Error - error decoding response body: expected value at line 1 column 1`
I've handled this and throw `MissingResponseData` instead to make it more readable to the end user
Ticket: https://mindvalley.atlassian.net/browse/PXP-633
> PXP-633: Better error handling if there is failure on JSON decode 

- cli/src/commands/tui/events/mod.rs
CLI crashed when sender event is not able to send the event to the event manager. To fix that used `is_error` instead of unwarp to gracefully handle the error
Ticket: https://mindvalley.atlassian.net/browse/PXP-641
> PXP-641: Handle event sender panic

- sdk/src/graphql/changelog.rs
- sdk/src/graphql/deployment.rs
- sdk/src/graphql/deployment_github.rs
- sdk/src/graphql/kubernetes.rs
- sdk/src/graphql/mod.rs
- sdk/src/graphql/pipeline.rs
This pull request addresses an issue where the v1 error handling format was accidently replaced with a new one. To ensure consistency across different API environments, a quick switch has been implemented in the CLI. The primary objective is to align the error code format uniformly, irrespective of the API environment.
Additionally, please note that a subsequent pull request will be submitted to clean up the deprecated or old error handling code, maintaining codebase hygiene.
Ticket: https://mindvalley.atlassian.net/browse/PXP-663
A follow-up pull request is planned to conduct a thorough cleanup of the outdated error handling code
> PXP-663: [CLI] Depreciate old error handling

- Cargo.lock
- cli/Cargo.toml
- cli/src/auth/google_cloud.rs
- cli/src/auth/okta.rs
- cli/src/auth/vault.rs
- cli/src/commands/application/logs.rs
- cli/src/commands/google/login.rs
- cli/src/commands/google/mod.rs
- cli/src/commands/init.rs
- cli/src/commands/login.rs
- cli/src/commands/mod.rs
- cli/src/commands/tui/events/network.rs
- cli/src/config.rs
- cli/src/wukong_client.rs
- cli/tests/application.rs
- cli/tests/application_instances.rs
- cli/tests/config.rs
- cli/tests/deployment.rs
- cli/tests/dev_config.rs
- cli/tests/pipeline.rs
- cli/tests/snapshots/config__wukong_config_list_success.snap
- cli/tests/snapshots/config__wukong_config_list_success_without_login.snap
Build the workflow for the wukong init command to satisfy the specifications. Details about the command inputs and outputs can be found [here](https://mindvalley.atlassian.net/wiki/spaces/PXP/pages/762773518/RFC17+-+New+Global+Init+UX).
Ticket: https://mindvalley.atlassian.net/browse/PXP-524
> PXP-638: [CLI] Implement new config

- cli/src/auth/google_cloud.rs
- cli/src/auth/okta.rs
- cli/src/commands/config/get.rs
- cli/src/commands/config/set.rs
- cli/src/commands/google/login.rs
- cli/src/commands/init.rs
- cli/src/commands/login.rs
- cli/src/commands/mod.rs
- cli/src/config.rs
- cli/src/loader.rs
- cli/tests/application.rs
- cli/tests/application_instances.rs
- cli/tests/config.rs
- cli/tests/deployment.rs
- cli/tests/dev_config.rs
- cli/tests/pipeline.rs
- cli/tests/snapshots/config__wukong_config_get_success.snap
- cli/tests/snapshots/config__wukong_config_list_success.snap
- cli/tests/snapshots/config__wukong_config_list_success_without_login.snap
We are already using the new input library, inquire, for the per-application initialization flow. It would be beneficial to do the same thing with the global initialization flow as well.
https://github.com/mindvalley/wukong-cli/assets/25294487/4dcf6df2-c19e-4c65-aba4-c47a39fa428e
Ticket: https://mindvalley.atlassian.net/browse/PXP-664
> PXP-664 refactor: replace global init with inquire library

- cli/src/commands/application/logs.rs
With the new clippy version the lint checks for function arguments of type &String, &Vec, &PathBuf, and Cow<_>. It will also suggest you replace .clone() calls with the appropriate .to_owned()/to_string() calls.
More info: https://rust-lang.github.io/rust-clippy/master/index.html#/ptr_arg
> Fix: Apply new clippy changes for for rust version (1.26.0)

- cli/src/commands/application/init.rs
This PR addresses an issue in the application initialization process where the CLI was not displaying all available GitHub Actions workflows during step #2. The root cause of the problem was identified as the exclusion of `.yaml` files when checking for workflows in the `.github/workflows` directory.
Ticket: [PXP-672](https://mindvalley.atlassian.net/browse/PXP-672)
[PXP-672]: https://mindvalley.atlassian.net/browse/PXP-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-672: [CLI] Include .yaml file types in application init workflow list

- cli/src/commands/application/init.rs
Currently, when running the application init, if there are no Github Actions workflows in the .github folder, the CLI will return error. To handle this case skip the workflow action if there is no file in the directly or path is not found
Ticket: [PXP-676](https://mindvalley.atlassian.net/browse/PXP-676)
[PXP-676]: https://mindvalley.atlassian.net/browse/PXP-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-676: [CLI] Skip workflow step on application init if empty

- cli/src/commands/mod.rs
Ticket: [PXP-675](https://mindvalley.atlassian.net/browse/PXP-675)
[PXP-675]: https://mindvalley.atlassian.net/browse/PXP-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-675: [CLI] Make canary flag enabled by default

- Cargo.lock
- cli/src/auth/google_cloud.rs
- cli/src/commands/tui/app.rs
- cli/src/commands/tui/events/network.rs
- cli/src/commands/tui/handlers/databases.rs
- cli/src/commands/tui/handlers/empty.rs
- cli/src/commands/tui/handlers/log_filter_exclude.rs
- cli/src/commands/tui/handlers/log_filter_include.rs
- cli/src/commands/tui/handlers/log_search.rs
- cli/src/commands/tui/handlers/logs.rs
- cli/src/commands/tui/handlers/middle.rs
- cli/src/commands/tui/handlers/mod.rs
- cli/src/commands/tui/handlers/namespace_selection.rs
- cli/src/commands/tui/handlers/time_filter_selection.rs
- cli/src/commands/tui/handlers/version_selection.rs
- cli/src/commands/tui/mod.rs
- cli/src/commands/tui/ui/appsignal.rs
- cli/src/commands/tui/ui/databases.rs
- cli/src/commands/tui/ui/middle.rs
- cli/src/commands/tui/ui/mod.rs
- cli/src/wukong_client.rs
- sdk/Cargo.toml
- sdk/build.rs
- sdk/src/error.rs
- sdk/src/services/gcloud/api/google.api.rs
- sdk/src/services/gcloud/api/google.cloud.sql.v1.rs
- sdk/src/services/gcloud/api/google.monitoring.v3.rs
- sdk/src/services/gcloud/mod.rs
In this PR we introduce a third panel called "Databases" that pulls metrics from GCloud using the protobuf generated modules by tonic for gcloud.
Ticket: https://mindvalley.atlassian.net/browse/PXP-660
* Network dispatching of new get_database_metrics mechanism.
* Changed `Block::Log` to `Block::Middle`
> PXP-660 feat: add cloudsql database metrics panel

- cli/src/commands/deployment/status.rs
Ticket: [PXP-685](https://mindvalley.atlassian.net/browse/PXP-685)
[PXP-685]: https://mindvalley.atlassian.net/browse/PXP-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-685: [CLI] Improve the warning when CloudSQL integration is not enabled

- README.md
- cli/src/application_config.rs
- cli/src/commands/application/init.rs
With the addition of [this](https://github.com/mindvalley/wukong-api-proxy/pull/177) feature, we can now let our devs configure slack notifications for their repo. 
In this PR, we introduce an additional prompt to enter the Slack Channel to which notifications of deployments should be sent in the `application init` flow. 
Setting a channel-name enables Slack notification for the repo with the given channel name.
Ticket: https://mindvalley.atlassian.net/browse/PXP-720
New prompt for Slack notification config in `application init`
The corresponding .wukong.toml file for the above operations:
```
[application]
name = "my-test-application"
enable = true
[application.workflows]
provider = "github_actions"
excluded_workflows = []
[[application.namespaces]]
type = "prod" …
```
> DX-731 feat: add slack notifications config into application init flow

- Cargo.lock
- cli/Cargo.toml
- cli/tests/snapshots/wukong__wukong_version_without_config_file.snap
Bumping the CLI version into `2.1.1`.  
Ticket:
* Bumping CLI version to `2.1.1`.  
> chore/bump version 2.1.1

- cli/src/commands/application/instances/connect.rs
- sdk/src/graphql/query/kubernetes_pods.graphql
- sdk/src/graphql/schema.json
- telemetry/src/lib.rs
In this PR, we update the kubernetes_pod query to additionally get the `node_name` and `cookie` for the pod and display those values along with a short instruction on how the user can connect to a selected node.
Ticket: [DX-805](https://mindvalley.atlassian.net/browse/DX-805)
The changes in action:
Testing out the provided details in a livebook:
Show pod connection details and instructions on how to use them in the `application instances connect` flow
Updated schema and kubernetes_pods.graphql to get `node_name` and `cookie` 
[DX-805]: https://mindvalley.atlassian.net/browse/DX-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DX-805 get and show pod connection details for livebook smart cell

- .github/workflows/ci.yml
- .github/workflows/release.yml
- cli/src/commands/application/instances/connect.rs
In this PR, we present the connectable instances in `application instances connect` in groups of "Main" or "Preview Instances".
Selecting either "Main" or "Preview" just keeps the user in the select context. User can only move forward by selecting one of the instances.
Ticket: https://mindvalley.atlassian.net/browse/DX-831
Updated the `application instances connect` Select menu to display pods grouped by "is_preview"
> feat: group pods by main or preview

- cli/src/application_config.rs
- cli/src/commands/application/init.rs
Add prompt for `continuous_delivery` flag in `wukong init` command and save selection in `wukong.toml`.
* **cli/src/application_config.rs**
- Add `continuous_delivery` field to `ApplicationNamespaceConfig` struct as a boolean.
- Provide a brief description of the `continuous_delivery` flag in the comments above the `ApplicationNamespaceConfig` struct.
* **cli/src/commands/application/init.rs**
- Add prompt for `continuous_delivery` flag in `configure_namespace` function.
- Include `continuous_delivery` flag in the namespace configuration based on user input.
- Update the generated `wukong.toml` file to include the `continuous_delivery` flag.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/mindvalley/wukong-cli/pull/233?shareId=d139318d-54 …
> Add continuous delivery flag to wukong init command
