src/commands/pipeline/ci_status.rs

Display empty `ci-status` result in table form.
Ticket: [PXP-390](https://mindvalley.atlassian.net/browse/PXP-390)

PXP-390: [CLI] Improve the output of the ci-status when running against branch without PR

---

Cargo.lock
Cargo.toml
src/commands/deployment/execute.rs
src/commands/pipeline/list.rs
src/graphql/changelog.rs
src/graphql/query/changelogs.graphql
src/graphql/schema.json

Ticket: [PXP-393](https://mindvalley.atlassian.net/browse/PXP-393) & [PXP-409](https://mindvalley.atlassian.net/browse/PXP-409)

PXP-393: [CLI] Makes CHANGELOG paginable using keyboard

---

README.md

Signed-off-by: Alex <alex.tuan@mindvalley.com>
Ticket:
* Add the KNOWN ISSUE section in REDAME

Add KNOWN ISSUE section

---

src/commands/deployment/execute.rs
src/error.rs
src/graphql/changelog.rs
src/graphql/deployment.rs
src/graphql/pipeline.rs

Ticket: [PXP-418](https://mindvalley.atlassian.net/browse/PXP-418)

PXP-418: [Wukong CLI] Asking user to continue to deploy when selecting the same build as current deployed ref.

---

src/config.rs
src/graphql/mod.rs

Fix clippy errors after updating to Rust 1.65.0.
Ticket:

Fix clippy errors

---

Cargo.lock
Cargo.toml
src/commands/deployment/execute.rs
src/commands/init.rs
src/commands/login.rs
src/main.rs
src/output/error.rs

Ticket: [PXP-419](https://mindvalley.atlassian.net/browse/PXP-419)

PXP-419: [Wukong CLI] Cursor disappear when terminating the interactive session in the middle.

---

README.md

Signed-off-by: Alex <alex.tuan@mindvalley.com>
Ticket:
* Correct the command to check Wukong CLI version.

Correct the command to check Wukong CLI version

---

src/commands/deployment/list.rs
src/graphql/deployment.rs
src/graphql/query/cd_pipelines.graphql
src/graphql/schema.json

Ticket: [PXP-423](https://mindvalley.atlassian.net/browse/PXP-423)

PXP-423: [CLI] Display the build artifact name when listing deployments

---

Cargo.lock
Cargo.toml
src/commands/deployment/execute.rs
src/commands/deployment/list.rs
src/commands/init.rs
src/commands/login.rs
src/commands/pipeline/ci_status.rs
src/commands/pipeline/describe.rs
src/commands/pipeline/list.rs
src/graphql/pipeline.rs
src/main.rs
src/output/mod.rs
src/output/tokenizer.rs

Ticket: [PXP-459](https://mindvalley.atlassian.net/browse/PXP-459)
- `This is PR #123` -> `[Token::Word("This"), Token::Whitespace, Token::Word("is"), Token::Whitespace, Token::Word("PR"), Token::Whitespace, Token::PR("#123")]`
before:
after:
[PXP-459]: https://mindvalley.atlassian.net/browse/PXP-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-459: [CLI] Do discovery on whether or not we can do text tokenisation on CLI outputs

---

completions/bash/wukong.bash
completions/fish/wukong.fish
completions/zsh/_wukong
src/commands/application/info.rs
src/commands/application/mod.rs
src/commands/mod.rs
src/graphql/application.rs
src/graphql/mod.rs
src/graphql/query/application.graphql
src/graphql/schema.json
src/main.rs

Ticket: [PXP-434](https://mindvalley.atlassian.net/browse/PXP-434)
[PXP-434]: https://mindvalley.atlassian.net/browse/PXP-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-434: [CLI] Implement the application info command

---

src/commands/deployment/rollback.rs

Ticket: [PXP-467](https://mindvalley.atlassian.net/browse/PXP-467)
[PXP-467]: https://mindvalley.atlassian.net/browse/PXP-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 PXP-467: [CLI] Generating a default changelog for the rollback operation (re-open)

---

src/commands/deployment/execute.rs
src/graphql/query/cd_pipeline.graphql
src/graphql/schema.json

…d build
Ticket: [PXP-468](https://mindvalley.atlassian.net/browse/PXP-468)
[PXP-468]: https://mindvalley.atlassian.net/browse/PXP-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-468: [CLI] Use the new field to determine what is the current deployed artifact

---

Cargo.lock
Cargo.toml
tests/snapshots/application__wukong_application_help.snap
tests/snapshots/completion__wukong_completion_bash.snap
tests/snapshots/completion__wukong_completion_fish.snap
tests/snapshots/completion__wukong_completion_help.snap
tests/snapshots/completion__wukong_completion_zsh.snap
tests/snapshots/config__wukong_config_get_should_failed_with_non_supported_field.snap
tests/snapshots/config__wukong_config_help.snap
tests/snapshots/config__wukong_config_set_should_failed_with_non_supported_field.snap
tests/snapshots/deployment__wukong_deployment_help.snap
tests/snapshots/pipeline__wukong_pipeline_help.snap
tests/snapshots/wukong__wukong_help_without_config_file.snap
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
Bump version to v0.0.5-beta1

Bump version to v0.0.5-beta1

---

src/commands/config.rs
src/telemetry.rs

Ticket: [PXP-481](https://mindvalley.atlassian.net/browse/PXP-481)
Before:
After:
[PXP-481]: https://mindvalley.atlassian.net/browse/PXP-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-481: [Wukong CLI] Telemetry panic when the `~/.config/wukong` path is not exists 

---

Cargo.lock
Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
Bump version to v0.0.5-beta2

Bump version to v0.0.5-beta2

---

src/commands/deployment/execute.rs

Ticket: [PXP-493](https://mindvalley.atlassian.net/browse/PXP-493)
before
after
[PXP-493]: https://mindvalley.atlassian.net/browse/PXP-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-493: [Wukong CLI] Fix the text alignment when listing build artifacts

---

src/commands/deployment/execute.rs

Fix clippy rule

---

Cargo.lock
Cargo.toml
src/lib.rs
src/utils/annotation.rs
src/utils/annotations.rs
src/utils/mod.rs

Ticket: [PXP-474](https://mindvalley.atlassian.net/browse/PXP-474)
[PXP-474]: https://mindvalley.atlassian.net/browse/PXP-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-474: [CLI] Develop the ability to read annotations in dev config

---

src/auth/mod.rs
src/commands/init.rs
src/commands/mod.rs

fix: show refresh token error using debug output

---

Cargo.lock
Cargo.toml
completions/bash/wukong.bash
completions/fish/wukong.fish
completions/zsh/_wukong
src/commands/dev/config_lint.rs
src/commands/dev/config_synthesizer.rs
src/commands/dev/mod.rs
src/commands/init.rs
src/commands/mod.rs
src/config.rs
src/error.rs
src/lib.rs
src/services/vault/client.rs
src/services/vault/mod.rs
src/utils/annotations.rs
tests/dev.rs
tests/snapshots/completion__wukong_completion_bash.snap
tests/snapshots/completion__wukong_completion_fish.snap
tests/snapshots/completion__wukong_completion_zsh.snap
tests/snapshots/dev__wukong_dev_config_lint_success.snap
tests/snapshots/dev__wukong_dev_config_synthesizer_success.snap
tests/snapshots/dev__wukong_dev_config_synthesizer_success.snap.new
tests/snapshots/dev__wukong_dev_help.snap

Ticket: [PXP-476](https://mindvalley.atlassian.net/browse/PXP-476)
[PXP-476]: https://mindvalley.atlassian.net/browse/PXP-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-476: [CLI] Develop the config synthesizer command

---

Cargo.lock
Cargo.toml
tests/dev.rs
tests/snapshots/dev__wukong_dev_config_lint_success.snap
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
* Add a new command, `dev config-synthesizer` to pull the secrets from Vault for Elixir app.
* Implement the retry mechanism to deal with API timeout.

Bump version to 0.0.7-rc1

---

Cargo.lock
Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
* Bump to version 0.0.7-rc2 before release.

Bump version before release

---

completions/bash/wukong.bash
completions/fish/wukong.fish
completions/zsh/_wukong
src/commands/application/logs.rs
src/commands/application/mod.rs
src/services/gcloud/mod.rs
tests/snapshots/completion__wukong_completion_bash.snap
tests/snapshots/completion__wukong_completion_fish.snap
tests/snapshots/completion__wukong_completion_zsh.snap

Ticket: [PXP-501](https://mindvalley.atlassian.net/browse/PXP-501)
[PXP-501]: https://mindvalley.atlassian.net/browse/PXP-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-501: [CLI] Implement the include & exclude flags

---

completions/bash/wukong.bash
completions/fish/wukong.fish
completions/zsh/_wukong
src/commands/application/logs.rs
src/commands/application/mod.rs
tests/snapshots/completion__wukong_completion_bash.snap
tests/snapshots/completion__wukong_completion_fish.snap
tests/snapshots/completion__wukong_completion_zsh.snap

Ticket: [PXP-503](https://mindvalley.atlassian.net/browse/PXP-503)
[PXP-503]: https://mindvalley.atlassian.net/browse/PXP-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-503: [CLI] Implement the url-mode flag

---

Cargo.lock
Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

This PR will bump the wukong-cli into version 1.0.0, as a preration for the release of the version to Mindvalley developers.  
Jira Epics & Tickets:  https://mindvalley.atlassian.net/projects/PXP/versions/10265/tab/release-report-all-issues  
Ticket:
* Bump the version of the package in Cargo.toml.  
* Upgrade to latest dependencies.

Bump version to 1.0.0

---

Cargo.lock
Cargo.toml
crates/elixir-linter/Cargo.lock
crates/elixir-linter/Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

- Bumping version to 1.0.2
- Bump version and dependencies
Ticket:
* Bump version to 1.0.2.  

chore/bump version 1.0.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
* Bump version to 1.0.3.  
* Update dependencies.

Bump version and update dependencies

---

Cargo.lock
Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
* Bump version to 1.1.0.  

Bump version to 1.1.0

---

Cargo.lock
Cargo.toml
tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
* Bump to version 1.1.1.  

Bump to version 1.1.1

---

cli/src/commands/dev/config/diff.rs
cli/src/commands/dev/config/utils.rs
cli/src/commands/tui/hotkey.rs
cli/src/commands/tui/mod.rs
cli/tests/deployment.rs
cli/tests/dev_config.rs
cli/tests/pipeline.rs
sdk/crates/elixir-linter/src/rules/no_env_in_dev_config.rs
sdk/crates/elixir-linter/src/rules/no_env_in_main_config.rs
sdk/crates/elixir-linter/src/rules/use_import_config_with_file_exists_checking.rs

Ticket: [PXP-584](https://mindvalley.atlassian.net/browse/PXP-584)
https://github.com/mindvalley/wukong-cli/assets/7545747/d9fa0195-639d-4165-b105-d2090cb95859
[PXP-584]: https://mindvalley.atlassian.net/browse/PXP-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-584: [CLI] Implement the hotkeys

---

cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/builds.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/namespace_selection.rs

> [!IMPORTANT]  
> This PR is implemented on top of #133 , so this PR is based on that branch.
Ticket: [PXP-581](https://mindvalley.atlassian.net/browse/PXP-581)
[PXP-581]: https://mindvalley.atlassian.net/browse/PXP-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-581: [CLI] Implement the deployment section

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/application/logs.rs
cli/src/commands/application/mod.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/mod.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/builds.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/logs.rs
cli/src/commands/tui/ui/namespace_selection.rs
cli/src/wukong_client.rs
sdk/src/graphql/schema.json

Ticket: [PXP-579](https://mindvalley.atlassian.net/browse/PXP-579)
[PXP-579]: https://mindvalley.atlassian.net/browse/PXP-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-579: [CLI] Implement the logs section

---

cli/src/commands/pipeline/mod.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/logs.rs
cli/src/output/table.rs

fix: fix errors from the latest dependencies

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/pipeline/mod.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/logs.rs
cli/src/output/table.rs
cli/tests/snapshots/completion__wukong_completion_bash.snap
cli/tests/snapshots/wukong__wukong_version_without_config_file.snap
sdk/Cargo.toml

In this PR, we will bump the version of the following crate:  
* `cli` to 2.0.0-alpha1.  
* `sdk` to 2.0.0.  
Ticket:
Bump version and update to latest dependencies.

Bump version and update to latest dependencies

---

cli/src/commands/tui/action.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/application.rs
cli/src/commands/tui/ui/mod.rs
cli/src/commands/tui/ui/namespace_selection.rs
cli/src/commands/tui/ui/version_selection.rs

Support a new hot key, <v> to select the version of an application, and fetch the data for other panels according to the selected version
Ticket: [https://mindvalley.atlassian.net/browse/PXP-600](https://mindvalley.atlassian.net/browse/PXP-600)

PXP-600: Display data from different version using hotkey

---

cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/application.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/namespace_selection.rs
cli/src/commands/tui/ui/version_selection.rs

API endpoints are being called on the TUI without proper verification of the namespace and version. 
Fixed by adjusting the order of API calls to ensure that namespace and version validation is performed before making API requests.
Ticket: https://mindvalley.atlassian.net/browse/PXP-613

PXP-613: Update API calls order

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/tui/action.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/mod.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/help.rs
cli/src/commands/tui/ui/logs.rs
cli/src/commands/tui/ui/mod.rs
cli/src/commands/tui/ui/namespace_selection.rs
cli/src/commands/tui/ui/version_selection.rs

Ticket: [PXP-597](https://mindvalley.atlassian.net/browse/PXP-597)
[PXP-597]: https://mindvalley.atlassian.net/browse/PXP-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-597: [CLI] Logs panel: Support search / filter for logs

---

cli/src/commands/deployment/execute.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/mod.rs
cli/src/commands/tui/handlers/build.rs
cli/src/commands/tui/handlers/common_key_events.rs
cli/src/commands/tui/handlers/deployment.rs
cli/src/commands/tui/handlers/empty.rs
cli/src/commands/tui/handlers/log_filter_exclude.rs
cli/src/commands/tui/handlers/log_filter_include.rs
cli/src/commands/tui/handlers/log_search.rs
cli/src/commands/tui/handlers/logs.rs
cli/src/commands/tui/handlers/mod.rs
cli/src/commands/tui/handlers/namespace_selection.rs
cli/src/commands/tui/handlers/version_selection.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/builds.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/empty.rs
cli/src/commands/tui/ui/logs.rs
cli/src/commands/tui/ui/mod.rs
cli/src/commands/tui/ui/namespace_selection.rs
cli/src/commands/tui/ui/util.rs
cli/src/commands/tui/ui/version_selection.rs
sdk/src/services/gcloud/api/google.api.rs

Add the ability to select a panel is needed because it will allow developer to perform certain actions with an individual panel. 
Ticket: https://mindvalley.atlassian.net/browse/PXP-608

PXP-608: Make panels selectable

---

Cargo.lock
cli/Cargo.toml
cli/tests/snapshots/completion__wukong_completion_fish.snap
cli/tests/snapshots/wukong__wukong_version_without_config_file.snap

Prepare to release the latest version of the CLI, version `2.0.0-alpha2`. 
Ticket:
* Bump CLI version to 2.0.0-alpha2.  

Bump version and update latest dependencies

---

cli/src/commands/tui/action.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/handlers/build.rs
cli/src/commands/tui/handlers/deployment.rs
cli/src/commands/tui/handlers/empty.rs
cli/src/commands/tui/handlers/log_filter_exclude.rs
cli/src/commands/tui/handlers/log_filter_include.rs
cli/src/commands/tui/handlers/log_search.rs
cli/src/commands/tui/handlers/logs.rs
cli/src/commands/tui/handlers/mod.rs
cli/src/commands/tui/handlers/namespace_selection.rs
cli/src/commands/tui/handlers/version_selection.rs
cli/src/commands/tui/mod.rs
cli/src/commands/tui/ui/builds.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/commands/tui/ui/logs.rs
cli/src/commands/tui/ui/mod.rs
sdk/src/services/gcloud/api/google.api.rs

> [!IMPORTANT]  
> This PR is implemented on top of #155 because I want to test the scrolling with expanded panel, so this PR is based on that branch.
Ticket: [PXP-610](https://mindvalley.atlassian.net/browse/PXP-610)
[PXP-610]: https://mindvalley.atlassian.net/browse/PXP-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-610: [CLI] Panel Expand

---

telemetry-macro/src/lib.rs
telemetry/src/lib.rs

Ticket: [PXP-625](https://mindvalley.atlassian.net/browse/PXP-625)
[PXP-625]: https://mindvalley.atlassian.net/browse/PXP-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-625: [CLI] Report the Wukong version to telemetry

---

cli/src/commands/tui/action.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/handlers/empty.rs
cli/src/commands/tui/handlers/logs.rs
cli/src/commands/tui/handlers/mod.rs
cli/src/commands/tui/handlers/time_filter_selection.rs
cli/src/commands/tui/handlers/version_selection.rs
cli/src/commands/tui/ui/mod.rs
cli/src/commands/tui/ui/time_filter_selection.rs

The hotkey on the ticket is `Ctrl+s`, but it is conflicted with the search input which is using the same hotkey, so for now I use the `Ctrl+r` for the time filter (it is temporary, we should change the hotkey).
Ticket: [PXP-599](https://mindvalley.atlassian.net/browse/PXP-599)
[PXP-599]: https://mindvalley.atlassian.net/browse/PXP-599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-599: [CLI] Logs panel: Support time filtering (Reopen to base on the main branch)

---

cli/src/wukong_client.rs

PXP-632: [CLI] Okta tokens did not being updated after refresh

---

Cargo.lock
cli/Cargo.toml
cli/tests/snapshots/wukong__wukong_version_without_config_file.snap

Prepare for the release of the `2.0.0-alpha3` version.  
Ticket:
* Bump version of the cli to `2.0.0-alpha3`.  

Bump version of the cli

---

README.md
cli/src/commands/mod.rs
cli/tests/config.rs
cli/tests/snapshots/config__wukong_config_list_success.snap

Update README to add installation steps.  
Ticket:
* Add installation steps to README.  
* Remove obsoleted warnings.

Update README to add installation steps

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/tui/action.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/handlers/logs.rs
cli/src/commands/tui/ui/logs.rs
cli/tests/config.rs

Ticket: [PXP-617](https://mindvalley.atlassian.net/browse/PXP-617)
[PXP-617]: https://mindvalley.atlassian.net/browse/PXP-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-617: [CLI] Logs Panel: Support line wrapping

---

cli/src/commands/tui/action.rs
cli/src/commands/tui/app.rs
cli/src/commands/tui/events/network.rs
cli/src/commands/tui/handlers/logs.rs
cli/src/commands/tui/handlers/mod.rs
cli/src/commands/tui/handlers/time_filter_selection.rs
cli/src/commands/tui/ui/mod.rs

Ticket: [PXP-638](https://mindvalley.atlassian.net/browse/PXP-638)
[PXP-638]: https://mindvalley.atlassian.net/browse/PXP-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-638: [CLI] Reached API limits on Google Logging

---

.github/workflows/release.yml

Update upload-artifact action to v4

---

.github/workflows/release.yml

Fix a typo in the download action

---

.github/workflows/release.yml

Add artifact download path to release workflow

---

.github/workflows/ci.yml
.github/workflows/release.yml

This PR will:
- update github actions to use latest versions

chore(github): update github actions

---

Cargo.lock
cli/Cargo.toml
cli/src/auth/vault.rs
cli/src/commands/deployment/status.rs
cli/src/commands/pipeline/mod.rs
cli/src/commands/tui/ui/deployment.rs
cli/src/output/table.rs
sdk/Cargo.toml
sdk/src/services/gcloud/api/google.api.rs
sdk/src/services/gcloud/api/google.cloud.sql.v1.rs
sdk/src/services/gcloud/mod.rs
telemetry/Cargo.toml

This PR will patch all the [security warnings](https://github.com/mindvalley/wukong-cli/security/dependabot) by upgrading our crates.
Ticket:

deps: upgrade dependencies to patch security warnings

---

cli/src/auth/google_cloud.rs
cli/src/commands/application/init.rs
cli/src/commands/deployment/status.rs
cli/src/commands/tui/events/network.rs
cli/src/error.rs
cli/src/output/error.rs
cli/src/output/table.rs
cli/tests/snapshots/application__wukong_application_info_should_failed_when_unauthenticated.snap
cli/tests/snapshots/config__wukong_config_list_should_failed_without_config_file.snap
cli/tests/snapshots/deployment__wukong_deployment_list_should_failed_when_config_file_not_exist.snap
cli/tests/snapshots/deployment__wukong_deployment_list_should_failed_when_unauthenticated.snap
cli/tests/snapshots/pipeline__wukong_pipeline_ci_status_should_failed_when_unauthenticated.snap
cli/tests/snapshots/pipeline__wukong_pipeline_describe_should_failed_when_unauthenticated.snap
cli/tests/snapshots/pipeline__wukong_pipeline_list_should_failed_when_unauthenticated.snap
sdk/src/services/gcloud/api/google.api.rs
sdk/src/services/gcloud/api/google.cloud.sql.v1.rs
sdk/src/services/gcloud/mod.rs

Ticket: [PXP-671](https://mindvalley.atlassian.net/browse/PXP-671)
[PXP-671]: https://mindvalley.atlassian.net/browse/PXP-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-671: [CLI] Implement the CloudSQL integration to the deployment status command

---

cli/src/commands/deployment/status.rs

chore: add telemetry for deployment status command

---

Cargo.lock
cli/Cargo.toml
cli/src/auth/google_cloud.rs
cli/tests/snapshots/wukong__wukong_version_without_config_file.snap

Ticket:
* Bump version of the CLI package.  

Bump version and dependencies

---

README.md
guides/upgrade_from_2.0.x_to_2.1.0.md

Because the version `2.1.0` contains a breaking changes in the Wukong CLI, we
are updating the README.md and adding a more detailed explanation about the changes.
Ticket:
* Adding a doc to explain the breaking changes.  
* Update README to highlight the breaking changes.

Update documentation about the breaking changes in version 2.1.0.

---

.github/workflows/ci.yml
Cargo.lock
cli/src/application_config.rs
cli/src/commands/application/init.rs
sdk/src/services/gcloud/mod.rs

We fix the entries for slack notification in .wukong.toml to reflect what WukongApiProxy is expecting
Ticket:
We update the entry to be like so:

DX-789 fix: update slack notification entry in .wukong.toml

---

cli/src/commands/application/init.rs

We add a prompt for the user to enter `allowed admins` (as a list of emails), to limit the ability of launching a liveview instance to these admins only.
An actual update to `wukong-ci-mock`'s `.wukong.toml` showed the config reflected in `ApplicationConfig` on Wukong prod.
Ticket: https://mindvalley.atlassian.net/browse/DX-766
Prompts for `allowed admins` in `application init` flow.

DX-766 feat: add `allowed admins` prompt into application init flow

---

Cargo.lock
cli/Cargo.toml
cli/tests/snapshots/wukong__wukong_version_without_config_file.snap

Bumping the `cli` create to version `2.1.2`.  
Ticket:
* Bumping version of the `cli` crate to `2.1.2`.  
* Update the dependencies.

Bump version of the cli and update to latest dependencies
